// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_4J6cixN7W-knircWioCKhOj2UONSkBg',
    appId: '1:829614774708:android:e0b5327c85ed7ab4fabae1',
    messagingSenderId: '829614774708',
    projectId: 'batsugame-share',
    storageBucket: 'batsugame-share.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAab1RDgOKZejM0EzEaEwUdFuqJs0kisBs',
    appId: '1:829614774708:ios:c1719c1ce1ed8c37fabae1',
    messagingSenderId: '829614774708',
    projectId: 'batsugame-share',
    storageBucket: 'batsugame-share.appspot.com',
    iosClientId: '829614774708-pcnm4hnce8vmar7pn35gefo2c5omiimf.apps.googleusercontent.com',
    iosBundleId: 'com.example.batsugameShare',
  );
}
